<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(MSBuildThisFileDirectory)..\..\..\..\Shared\Back\src\domain\GesFer.Shared.Back.Domain\GesFer.Shared.Back.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\Shared\Back\src\domain\GesFer.Shared.Back.Domain\GesFer.Shared.Back.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\Shared\Back\GesFer.Shared.Back.Domain.csproj" />
  </ItemGroup>

</Project>

