<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>GesFer.Shared.Back.Application</RootNamespace>
    <!-- Disable default compile items to avoid duplicate includes and exclude everything by default -->
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="GesFer.Shared.Back.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.8.0" />
    <PackageReference Include="MediatR" Version="12.2.0" />
  </ItemGroup>

  <ItemGroup>
    <!-- Explicitly Include ONLY Abstractions -->
    <Compile Include="Abstractions\**\*.cs" />
  </ItemGroup>

</Project>
